In [1]:
import pandas as pd

In [2]:
df_only_origin = pd.read_csv('D:/ai/Downloads/Data/apt/행정안전부_지역별(행정동) 성별 연령별 주민등록 1인세대수_20241130.csv', encoding='cp949')
df_only_origin

,행정기관코드,기준연월,시도명,시군구명,읍면동명,계,남자,여자,0세남자,1세남자,...,101세여자,102세여자,103세여자,104세여자,105세여자,106세여자,107세여자,108세여자,109세여자,110세이상 여자
0,1111051500,2024-11-30,서울특별시,종로구,청운효자동,1928,719,1209,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1111053000,2024-11-30,서울특별시,종로구,사직동,2332,906,1426,0,0,...,1,0,0,0,0,0,0,0,0,0
2,1111054000,2024-11-30,서울특별시,종로구,삼청동,545,267,278,0,0,...,0,0,0,0,0,0,0,0,0,0
3,1111055000,2024-11-30,서울특별시,종로구,부암동,1665,677,988,0,0,...,0,0,0,0,0,0,0,0,0,0
4,1111056000,2024-11-30,서울특별시,종로구,평창동,2264,871,1393,0,0,...,1,2,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3609,5280038000,2024-11-30,전북특별자치도,부안군,백산면,905,417,488,0,0,...,0,0,0,0,0,0,0,0,0,0
3610,5280039000,2024-11-30,전북특별자치도,부안군,상서면,748,355,393,0,0,...,0,0,0,0,0,0,0,0,0,0
3611,5280040000,2024-11-30,전북특별자치도,부안군,하서면,884,413,471,0,0,...,0,1,0,0,0,0,0,0,0,0
3612,5280041000,2024-11-30,전북특별자치도,부안군,줄포면,882,414,468,0,0,...,0,0,0,0,0,0,0,0,0,0
3613,5280042000,2024-11-30,전북특별자치도,부안군,위도면,526,312,214,0,0,...,0,1,0,0,0,0,0,0,0,0

In [3]:
df_only=df_only_origin.drop(['행정기관코드','기준연월','계','남자','여자',],axis=1)
df_only=df_only.drop([f'{x}세남자' for x in range(18,110)],axis=1)
df_only=df_only.drop([f'{x}세여자' for x in range(18,110)],axis=1)
df_only=df_only.drop(['110세이상 남자','110세이상 여자'],axis=1)
df_only['18세미만 1인가구수']=df_only.iloc[:,3:].sum(axis=1)
df_only=df_only.drop(list(df_only.columns[3:-1]),axis=1)
df_only=df_only.drop(list(df_only[df_only['18세미만 1인가구수']==0].index),axis=0)

In [4]:
df_only

          시도명 시군구명 읍면동명  18세미만 1인가구수
1       서울특별시  종로구  사직동            2
2       서울특별시  종로구  삼청동            1
3       서울특별시  종로구  부암동            2
4       서울특별시  종로구  평창동           12
6       서울특별시  종로구  교남동            3
...       ...  ...  ...          ...
3607  전북특별자치도  부안군  변산면            1
3608  전북특별자치도  부안군  진서면            2
3609  전북특별자치도  부안군  백산면            1
3611  전북특별자치도  부안군  하서면            1
3612  전북특별자치도  부안군  줄포면            1

[2411 rows x 4 columns]

In [5]:
df_only.sort_values('18세미만 1인가구수',ascending=False)

          시도명 시군구명   읍면동명  18세미만 1인가구수
3105     경상남도  거창군    거창읍          371
2561     경상북도  김천시    대곡동          357
2555     경상북도  김천시    대덕면          203
2613     경상북도  영주시    풍기읍          185
2680     경상북도  문경시    영순면          163
...       ...  ...    ...          ...
1063    대전광역시   중구    용두동            1
2523     경상북도  경주시  문무대왕면            1
2524     경상북도  경주시    양남면            1
1062    대전광역시   중구    부사동            1
3612  전북특별자치도  부안군    줄포면            1

[2411 rows x 4 columns]

In [6]:
df_only.to_csv('D:/ai/Downloads/Data/apt/1인가구.csv',index=False)