In [2]:
from selenium import webdriver
from selenium.webdriver.common.by import By
import time
import datetime
from dateutil.relativedelta import relativedelta
import os
import pandas as pd

In [2]:
dv = webdriver.Chrome()
dv.get('https://rt.molit.go.kr/pt/xls/xls.do?mobileAt=')

In [3]:
start_date=datetime.date(2010,1,1)
end_date=datetime.date(2025,1,6)
from_date=end_date-relativedelta(months=1)+relativedelta(days=1)
to_date=end_date

In [6]:
start_date=datetime.date(2010,1,1)
end_date=datetime.date(2017,9,9)
from_date=end_date-relativedelta(months=1)+relativedelta(days=1)
to_date=end_date

In [9]:
start_date=datetime.date(2010,1,1)
end_date=datetime.date(2017,1,17)
from_date=end_date-relativedelta(months=1)+relativedelta(days=1)
to_date=end_date

In [10]:
def get_csv_data(from_date,to_date):
    elem = dv.find_element(By.NAME, 'srhFromDt')
    elem.clear()
    elem.send_keys(from_date.year)
    elem.send_keys('{:02}'.format(from_date.month))
    elem.send_keys('{:02}'.format(from_date.day))
    elem2 = dv.find_element(By.NAME, 'srhToDt')
    elem2.clear()
    elem2.send_keys(to_date.year)
    elem2.send_keys('{:02}'.format(to_date.month))
    elem2.send_keys('{:02}'.format(to_date.day))
    btn_elem = dv.find_elements(By.CLASS_NAME, 'ifdata-search-result')[1]
    btn_elem.click()
    time.sleep(10)

In [11]:
while(from_date>start_date):
    get_csv_data(from_date,to_date)
    to_date=from_date
    from_date=to_date-relativedelta(months=1)+relativedelta(days=1)

UnexpectedAlertPresentException: Alert Text: 다운로드에 실패하였습니다.
Message: unexpected alert open: {Alert text : 다운로드에 실패하였습니다.}
  (Session info: chrome=131.0.6778.205)
Stacktrace:
	GetHandleVerifier [0x00007FF754FDFB05+28789]
	(No symbol) [0x00007FF754F486E0]
	(No symbol) [0x00007FF754DE592A]
	(No symbol) [0x00007FF754E801F4]
	(No symbol) [0x00007FF754E5F1E3]
	(No symbol) [0x00007FF754E2A938]
	(No symbol) [0x00007FF754E2BAA1]
	GetHandleVerifier [0x00007FF75531933D+3410093]
	GetHandleVerifier [0x00007FF75532E7DD+3497293]
	GetHandleVerifier [0x00007FF755322A73+3448803]
	GetHandleVerifier [0x00007FF7550A7BBB+848171]
	(No symbol) [0x00007FF754F53C3F]
	(No symbol) [0x00007FF754F4F6E4]
	(No symbol) [0x00007FF754F4F87D]
	(No symbol) [0x00007FF754F3ED49]
	BaseThreadInitThunk [0x00007FFB5AE07BD4+20]
	RtlUserThreadStart [0x00007FFB5C70CED1+33]

In [180]:
filepath='D:/ai/Downloads/Data/apt/실거래가'
filelist=os.listdir(filepath)

In [181]:
filelist

['아파트(매매)_실거래가_20250107122634.csv',
 '아파트(매매)_실거래가_20250107122644.csv',
 '아파트(매매)_실거래가_20250107122655.csv',
 '아파트(매매)_실거래가_20250107122706.csv',
 '아파트(매매)_실거래가_20250107122717.csv',
 '아파트(매매)_실거래가_20250107122728.csv',
 '아파트(매매)_실거래가_20250107122739.csv',
 '아파트(매매)_실거래가_20250107122750.csv',
 '아파트(매매)_실거래가_20250107122800.csv',
 '아파트(매매)_실거래가_20250107122811.csv',
 '아파트(매매)_실거래가_20250107122821.csv',
 '아파트(매매)_실거래가_20250107122832.csv',
 '아파트(매매)_실거래가_20250107122842.csv',
 '아파트(매매)_실거래가_20250107122853.csv',
 '아파트(매매)_실거래가_20250107122903.csv',
 '아파트(매매)_실거래가_20250107122914.csv',
 '아파트(매매)_실거래가_20250107122925.csv',
 '아파트(매매)_실거래가_20250107122936.csv',
 '아파트(매매)_실거래가_20250107122946.csv',
 '아파트(매매)_실거래가_20250107122957.csv',
 '아파트(매매)_실거래가_20250107123008.csv',
 '아파트(매매)_실거래가_20250107123018.csv',
 '아파트(매매)_실거래가_20250107123029.csv',
 '아파트(매매)_실거래가_20250107123040.csv',
 '아파트(매매)_실거래가_20250107123050.csv',
 '아파트(매매)_실거래가_20250107123100.csv',
 '아파트(매매)_실거래가_20250107123111.csv',
 '아파트(매매)_실거래가_20250107123122.csv',
 '아파트(매매)_실거래가_20250107123133.csv',
 '아파트(매매)_실거래가_20250107123143.csv',
 '아파트(매매)_실거래가_20250107123154.csv',
 '아파트(매매)_실거래가_20250107123205.csv',
 '아파트(매매)_실거래가_20250107123216.csv',
 '아파트(매매)_실거래가_20250107123227.csv',
 '아파트(매매)_실거래가_20250107123238.csv',
 '아파트(매매)_실거래가_20250107123248.csv',
 '아파트(매매)_실거래가_20250107123259.csv',
 '아파트(매매)_실거래가_20250107123310.csv',
 '아파트(매매)_실거래가_20250107123321.csv',
 '아파트(매매)_실거래가_20250107123332.csv',
 '아파트(매매)_실거래가_20250107123343.csv',
 '아파트(매매)_실거래가_20250107123355.csv',
 '아파트(매매)_실거래가_20250107123405.csv',
 '아파트(매매)_실거래가_20250107123416.csv',
 '아파트(매매)_실거래가_20250107123427.csv',
 '아파트(매매)_실거래가_20250107123438.csv',
 '아파트(매매)_실거래가_20250107123449.csv',
 '아파트(매매)_실거래가_20250107123500.csv',
 '아파트(매매)_실거래가_20250107123511.csv',
 '아파트(매매)_실거래가_20250107123522.csv',
 '아파트(매매)_실거래가_20250107123545.csv',
 '아파트(매매)_실거래가_20250107123556.csv',
 '아파트(매매)_실거래가_20250107123606.csv',
 '아파트(매매)_실거래가_20250107123617.csv',
 '아파트(매매)_실거래가_20250107123629.csv',
 '아파트(매매)_실거래가_20250107123643.csv',
 '아파트(매매)_실거래가_20250107123652.csv',
 '아파트(매매)_실거래가_20250107123702.csv',
 '아파트(매매)_실거래가_20250107123725.csv',
 '아파트(매매)_실거래가_20250107123736.csv',
 '아파트(매매)_실거래가_20250107123748.csv',
 '아파트(매매)_실거래가_20250107123759.csv',
 '아파트(매매)_실거래가_20250107123810.csv',
 '아파트(매매)_실거래가_20250107123821.csv',
 '아파트(매매)_실거래가_20250107123832.csv',
 '아파트(매매)_실거래가_20250107123843.csv',
 '아파트(매매)_실거래가_20250107123854.csv',
 '아파트(매매)_실거래가_20250107123905.csv',
 '아파트(매매)_실거래가_20250107123916.csv',
 '아파트(매매)_실거래가_20250107123927.csv',
 '아파트(매매)_실거래가_20250107123939.csv',
 '아파트(매매)_실거래가_20250107123950.csv',
 '아파트(매매)_실거래가_20250107124001.csv',
 '아파트(매매)_실거래가_20250107124012.csv',
 '아파트(매매)_실거래가_20250107124023.csv',
 '아파트(매매)_실거래가_20250107124035.csv',
 '아파트(매매)_실거래가_20250107124047.csv',
 '아파트(매매)_실거래가_20250107124057.csv',
 '아파트(매매)_실거래가_20250107124108.csv',
 '아파트(매매)_실거래가_20250107124119.csv',
 '아파트(매매)_실거래가_20250107124130.csv',
 '아파트(매매)_실거래가_20250107124141.csv',
 '아파트(매매)_실거래가_20250107124153.csv',
 '아파트(매매)_실거래가_20250107124204.csv',
 '아파트(매매)_실거래가_20250107124215.csv',
 '아파트(매매)_실거래가_20250107124226.csv',
 '아파트(매매)_실거래가_20250107124238.csv',
 '아파트(매매)_실거래가_20250107124249.csv',
 '아파트(매매)_실거래가_20250107124259.csv',
 '아파트(매매)_실거래가_20250107124924.csv',
 '아파트(매매)_실거래가_20250107124936.csv',
 '아파트(매매)_실거래가_20250107124947.csv',
 '아파트(매매)_실거래가_20250107124959.csv',
 '아파트(매매)_실거래가_20250107125009.csv',
 '아파트(매매)_실거래가_20250107125021.csv',
 '아파트(매매)_실거래가_20250107125031.csv',
 '아파트(매매)_실거래가_20250107125042.csv']

In [182]:
df= pd.DataFrame()
for file_name in filelist:
    try:
        new_df=pd.read_csv(f'D:/ai/Downloads/Data/apt/실거래가/{file_name}',encoding='cp949',skiprows=15)
        df=pd.concat([df,new_df])
    except:
        print(file_name,'read 실패')
display(df)

,NO,시군구,번지,본번,부번,단지명,전용면적(㎡),계약년월,계약일,거래금액(만원),동,층,매수자,매도자,건축년도,도로명,해제사유발생일,거래유형,중개사소재지,등기일자
0,1,부산광역시 기장군 정관읍 모전리,728,728,0,동일스위트3차,84.9174,202501,6,"28,500",-,13,개인,개인,2014,9,-,중개거래,부산 기장군,-
1,2,광주광역시 광산구 산정동,1056,1056,0,부영애시앙2차,84.8198,202501,6,"26,500",-,10,개인,개인,2008,목련로 41,-,중개거래,광주 광산구,-
2,3,세종특별자치시 장군면 금암리,268,268,0,금암그린임대아파트,30.7568,202501,6,"3,280",-,1,개인,개인,2000,대학길 56-7,-,중개거래,대전 대덕구,-
3,4,서울특별시 노원구 중계동,587,587,0,양지마을(대림)1,84.9000,202501,6,"94,500",-,16,개인,개인,1998,덕릉로71길 30,-,중개거래,서울 노원구,-
4,5,서울특별시 금천구 시흥동,952,952,0,낙원,59.6800,202501,6,"28,000",-,2,개인,개인,1996,시흥대로26길 16,-,직거래,-,-
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36206,36207,경기도 부천시 원미구 역곡동,409,409,0,"부천동부센트레빌1,2단지",84.9900,201701,17,"38,000",-,13,-,-,2006,역곡로45번길 36,-,-,-,-
36207,36208,경상북도 칠곡군 북삼읍 인평리,1036,1036,0,오태현진,84.8700,201701,17,"14,200",-,5,-,-,1999,금오대로10길 35,-,-,-,-
36208,36209,충청남도 당진시 순성면 봉소리,423,423,0,순성한영,80.2600,201701,17,"8,600",-,5,-,-,2003,순성로 441,-,-,-,-
36209,36210,강원특별자치도 홍천군 홍천읍 하오안리,155,155,0,삼호2차,48.2020,201701,17,"6,400",-,5,-,-,2000,구시울1길 25,-,-,-,-
36210,36211,충청남도 금산군 금산읍 중도리,21-21,21,21,낙원아파트,49.6526,201701,17,"6,000",-,5,-,-,1999,약초로 18,-,-,-,-

In [187]:
df=df[df['계약년월']>=202001]

In [188]:
df.to_csv('D:/ai/Downloads/Data/apt/실거래가.csv',index=False)

In [271]:
df=pd.read_csv('D:/ai/Downloads/Data/apt/실거래가.csv')

In [272]:
df

,NO,시군구,번지,본번,부번,단지명,전용면적(㎡),계약년월,계약일,거래금액(만원),동,층,매수자,매도자,건축년도,도로명,해제사유발생일,거래유형,중개사소재지,등기일자
0,1,부산광역시 기장군 정관읍 모전리,728,728,0,동일스위트3차,84.9174,202501,6,"28,500",-,13,개인,개인,2014,9,-,중개거래,부산 기장군,-
1,2,광주광역시 광산구 산정동,1056,1056,0,부영애시앙2차,84.8198,202501,6,"26,500",-,10,개인,개인,2008,목련로 41,-,중개거래,광주 광산구,-
2,3,세종특별자치시 장군면 금암리,268,268,0,금암그린임대아파트,30.7568,202501,6,"3,280",-,1,개인,개인,2000,대학길 56-7,-,중개거래,대전 대덕구,-
3,4,서울특별시 노원구 중계동,587,587,0,양지마을(대림)1,84.9000,202501,6,"94,500",-,16,개인,개인,1998,덕릉로71길 30,-,중개거래,서울 노원구,-
4,5,서울특별시 금천구 시흥동,952,952,0,낙원,59.6800,202501,6,"28,000",-,2,개인,개인,1996,시흥대로26길 16,-,직거래,-,-
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2544079,18108,충청북도 청주시 흥덕구 가경동,1510,1510,0,세원가경골,59.7600,202001,1,"13,300",-,3,-,-,1997,가경로 134,-,-,-,-
2544080,18109,충청남도 천안시 동남구 안서동,304-1,304,1,동보스타빌,24.1800,202001,1,"5,600",-,5,-,-,1996,각원사길 59-5,-,-,-,-
2544081,18110,경기도 시흥시 월곶동,994,994,0,월곶4차풍림아이원,84.8420,202001,1,"25,600",-,18,-,-,2006,월곶중앙로14번길 9,-,-,-,-
2544082,18111,경기도 양주시 고읍동,451,451,0,산내들마을우미린아파트,84.9929,202001,1,"36,000",-,15,-,-,2009,고읍로35번길 8,-,-,-,-
2544083,18112,경기도 남양주시 다산동,6029,6029,0,다산롯데캐슬,84.9700,202001,1,"72,000",-,19,-,-,2017,다산중앙로146번길 7,-,-,-,-

In [274]:
df_modify=df
df_modify=df_modify.drop(['NO','번지','본번','부번','단지명',\
                          '계약년월','계약일','동','층','매수자','매도자','건축년도','도로명','해제사유발생일',\
                          '거래유형','중개사소재지','등기일자',],axis=1)
df_modify['시도명']=[df['시군구'][x].split(' ')[0] for x in range(len(df.index))]
df_modify['시군구명']=[df['시군구'][x].split(' ')[1] for x in range(len(df.index))]
df_modify['읍면동명']=[df['시군구'][x].split(' ')[2] for x in range(len(df.index))]
df_modify

                       시군구  전용면적(㎡) 거래금액(만원)      시도명  시군구명 읍면동명
0        부산광역시 기장군 정관읍 모전리  84.9174   28,500    부산광역시   기장군  정관읍
1            광주광역시 광산구 산정동  84.8198   26,500    광주광역시   광산구  산정동
2         세종특별자치시  장군면 금암리  30.7568    3,280  세종특별자치시        장군면
3            서울특별시 노원구 중계동  84.9000   94,500    서울특별시   노원구  중계동
4            서울특별시 금천구 시흥동  59.6800   28,000    서울특별시   금천구  시흥동
...                    ...      ...      ...      ...   ...  ...
2544079   충청북도 청주시 흥덕구 가경동  59.7600   13,300     충청북도   청주시  흥덕구
2544080   충청남도 천안시 동남구 안서동  24.1800    5,600     충청남도   천안시  동남구
2544081        경기도 시흥시 월곶동  84.8420   25,600      경기도   시흥시  월곶동
2544082        경기도 양주시 고읍동  84.9929   36,000      경기도   양주시  고읍동
2544083       경기도 남양주시 다산동  84.9700   72,000      경기도  남양주시  다산동

[2544084 rows x 6 columns]

In [275]:
df_modify['거래금액(만원)']=df_modify['거래금액(만원)'].str.replace(',','').astype(int)
df_modify['면적당금액(만원)']=round(df_modify['거래금액(만원)']/df_modify['전용면적(㎡)'])
df_modify=df_modify.drop(['전용면적(㎡)','거래금액(만원)'],axis=1)
df_modify

                       시군구      시도명  시군구명 읍면동명  면적당금액(만원)
0        부산광역시 기장군 정관읍 모전리    부산광역시   기장군  정관읍      336.0
1            광주광역시 광산구 산정동    광주광역시   광산구  산정동      312.0
2         세종특별자치시  장군면 금암리  세종특별자치시        장군면      107.0
3            서울특별시 노원구 중계동    서울특별시   노원구  중계동     1113.0
4            서울특별시 금천구 시흥동    서울특별시   금천구  시흥동      469.0
...                    ...      ...   ...  ...        ...
2544079   충청북도 청주시 흥덕구 가경동     충청북도   청주시  흥덕구      223.0
2544080   충청남도 천안시 동남구 안서동     충청남도   천안시  동남구      232.0
2544081        경기도 시흥시 월곶동      경기도   시흥시  월곶동      302.0
2544082        경기도 양주시 고읍동      경기도   양주시  고읍동      424.0
2544083       경기도 남양주시 다산동      경기도  남양주시  다산동      847.0

[2544084 rows x 5 columns]

In [276]:
df_modify=round(df_modify.groupby(['시도명','시군구명','읍면동명'],as_index=False).mean())
df_modify

          시도명 시군구명 읍면동명  면적당금액(만원)
0     강원특별자치도  강릉시  견소동      303.0
1     강원특별자치도  강릉시   교동      311.0
2     강원특별자치도  강릉시  금학동      321.0
3     강원특별자치도  강릉시  남문동      181.0
4     강원특별자치도  강릉시  내곡동      217.0
...       ...  ...  ...        ...
2362     충청북도  충주시  지현동      155.0
2363     충청북도  충주시  충의동       81.0
2364     충청북도  충주시  칠금동      217.0
2365     충청북도  충주시   풍동       95.0
2366     충청북도  충주시  호암동      210.0

[2367 rows x 4 columns]

In [277]:
df_modify.to_csv('D:/ai/Downloads/Data/apt/실거래가_정리.csv',index=False)